config/routes.rb
Rails.application.routes.draw do
  resources :templates

end

app/models/template.rb
class Template < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  # GET /templates
  # GET /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render :show, status: :created, location: @template }
      else
        format.html { render :new }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1
  # PATCH/PUT /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to templates_url, notice: 'Template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_params
      params.require(:template).permit(:goal, :type, :agenda, :required, :optional, :preparation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgendaTemplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :goal %><br>
    <%= f.text_field :goal %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda %>
  </div>
  <div class="field">
    <%= f.label :required %><br>
    <%= f.text_field :required %>
  </div>
  <div class="field">
    <%= f.label :optional %><br>
    <%= f.text_field :optional %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br>
    <%= f.text_area :preparation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Templates</h1>

<table>
  <thead>
    <tr>
      <th>Goal</th>
      <th>Type</th>
      <th>Agenda</th>
      <th>Required</th>
      <th>Optional</th>
      <th>Preparation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.goal %></td>
        <td><%= template.type %></td>
        <td><%= template.agenda %></td>
        <td><%= template.required %></td>
        <td><%= template.optional %></td>
        <td><%= template.preparation %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @template.goal %>
</p>

<p>
  <strong>Type:</strong>
  <%= @template.type %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @template.agenda %>
</p>

<p>
  <strong>Required:</strong>
  <%= @template.required %>
</p>

<p>
  <strong>Optional:</strong>
  <%= @template.optional %>
</p>

<p>
  <strong>Preparation:</strong>
  <%= @template.preparation %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>